slam_toolbox:
  ros__parameters:
    # ROS Parameters
    use_sim_time: true
    
    # tf
    map_frame: map
    base_frame: base_link
    odom_frame: odom
    map_update_interval: 5.0
    
    # Scan matching parameters
    max_laser_range: 20.0
    minimum_time_interval: 0.2
    transform_timeout: 0.2
    update_rate: 5.0
    
    # Optimization parameters
    max_iterations: 20
    smat_gain: 0.05
    smat_thresh: 0.05
    
    # Resolution parameters
    resolution: 0.05
    minimum_time_interval: 0.2
    transform_timeout: 0.2
    update_rate: 5.0
    
    # Scan matcher parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_time_interval: 0.2
    transform_timeout: 0.2
    update_rate: 5.0
    
    # Loop closure parameters
    use_loop_closure: true
    loop_closure_scan_valid_rate: 0.25
    loop_closure_search_valid_rate: 0.24
    loop_closure_minimum_chain_size: 10
    loop_closure_scan_buffer_size: 10
    loop_closure_scan_buffer_maximum_scan_distance_cumulative: 20.0
    loop_closure_scan_buffer_maximum_scan_distance_cumulative_squared: 400.0
    
    # Correlation parameters
    correlation_ratio: 0.3
    correlation_loop_maximum_distance: 4.0
    correlation_loop_maximum_distance_squared: 16.0
    
    # Scan matcher parameters
    scan_matcher_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
    
    # Debug parameters
    debug_logging: false 